version: '3.5'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: parts
      MYSQL_USER: scraper
      MYSQL_PASSWORD: Hunter2
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  postgresdb:
    # Need to create a table for this db
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  master:
    container_name: masterbase
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - postgresdb
    ports:
      - '5000:5000'
    expose:
      - '5000'
    volumes:
      - './server:/app'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SCRAPE_TIMEOUT=${SCRAPE_TIMEOUT}
      - NUM_OF_URLS=${NUM_OF_URLS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
