version: '3.5'
services:
  mysqldb:
    image: mysql:5.7
    hostname: mysqlbase
    container_name: mysql_db
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: parts
      MYSQL_USER: scraper
      MYSQL_PASSWORD: Hunter2
    networks:
      - backend

  postgresdb:
    hostname: postgresbase
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend
  
  master:
    container_name: masterbase
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    links:
      - "mysqldb:database"
    depends_on:
      - postgresdb
    ports:
      - '5000:5000'
    expose:
      - 5000
    volumes:
      - './server:/app'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'